[package]
name = "handle-errors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.3"
serde_derive = "1.0"
serde = "1.0"
diesel = { version = "2.0.2", features = ["postgres", "r2d2"] }